/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// 애플리케이션 메인클래스
// 애플리케이션을 실행할때 이 클래스를 실행한다.
package com.eomcs.lms;

import java.util.Scanner;

public class App2 {

  static Scanner scan;

  public static void main(String[] args) {
    scan = new Scanner(System.in);

    int no = getIntValue("번호?");
    String name = getStringValue("이름?");
    String email = getStringValue("이메일?");
    String password = getStringValue("암호?");
    String image = getStringValue("사진?");
    String phone = getStringValue("전화?");
    java.sql.Date joinDate = getDateValue("가입일?");

    System.out.println();

    System.out.println("번호: " + no);
    System.out.println("이름: " + name);
    System.out.println("이메일: " + email);
    System.out.println("암호: " + password);
    System.out.println("사진: " + image);
    System.out.println("전화: " + phone);
    System.out.println("가입일: " + joinDate);
  }

  private static java.sql.Date getDateValue(String message) {
    while (true) {
      try {
        System.out.print(message);
        return java.sql.Date.valueOf(scan.nextLine());
      } catch (IllegalArgumentException e) {
        System.out.println("2019-07-05 형식으로 입력하세요");
      }
    }
  }

  private static int getIntValue(String message) {
    while (true) {
      try {
        System.out.print(message);
        return Integer.parseInt(scan.nextLine());
      } catch (NumberFormatException e) {
        System.out.println("숫자를 입력하세요");
      }
    }
  }

  private static String getStringValue(String message) {
    while (true) {
      System.out.print(message);
      return scan.nextLine();
    }
  }

}
