/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// 애플리케이션 메인클래스
// 애플리케이션을 실행할때 이 클래스를 실행한다.
package com.eomcs.lms;

import java.util.Scanner;
import java.sql.Date;

public class App3 {

  static Scanner scan;

  public static void main(String[] args) {

    scan = new Scanner(System.in);

    Board[] boards = new Board[100];

    int i = 0;
    for (i = 0; i < boards.length; i++) {

      Board board = new Board();

      board.no = getIntValue("번호?");
      board.contents = getStringValue("내용?");
      board.createdDate = new Date(System.currentTimeMillis());
      board.viewCount = getIntValue("조회수?");
      
      boards[i] = board;

      System.out.println("계속입력하시겠습니까? (y/n)");
      String response = scan.nextLine();

      if (response.equals("n")) {
        break;
      }
    }
    for (int i2 = 0; i2 <= i; i2++) {
      Board board = boards[i2];
      System.out.printf("%s,%s,%s,%s\n", board.no, board.contents, board.createdDate,
          board.viewCount);
    }
    System.out.println();
  }

  private static int getIntValue(String message) {
    while (true) {
      try {
        System.out.print(message);
        return Integer.parseInt(scan.nextLine());
      } catch (NumberFormatException e) {
        System.out.println("숫자를 입력하세요");
      }
    }
  }

  private static String getStringValue(String message) {
    while (true) {
      System.out.print(message);
      return scan.nextLine();
    }
  }

}
