/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// 애플리케이션 메인클래스
// 애플리케이션을 실행할때 이 클래스를 실행한다.
package com.eomcs.lms;

import java.util.Scanner;
import java.sql.Date;

public class App2 {

  static Scanner scan;

  public static void main(String[] args) {
    scan = new Scanner(System.in);

    Member[] members = new Member[100];

    int i = 0;

    for (i = 0; i < members.length; i++) {

      Member member = new Member();

      member.no = getIntValue("번호?");
      member.name = getStringValue("이름?");
      member.email = getStringValue("이메일?");
      member.password = getStringValue("암호?");
      member.photo = getStringValue("사진?");
      member.tel = getStringValue("전화?");
      member.registeredDate = getDateValue("가입일?");

      members[i] = member;

      System.out.println("계속입력하시겠습니까? (y/n)");
      String response = scan.nextLine();

      if (response.equals("n")) {
        break;
      }
    }
    for (int i2 = 0; i2 <= i; i2++) {
      Member member = members[i2];
      System.out.printf("%s,%s,%s,%s,%s,%s,%s\n", member.no, member.name, member.email,
          member.password, member.photo, member.tel, member.registeredDate);
    }

    System.out.println();
  }

  private static Date getDateValue(String message) {
    while (true) {
      try {
        System.out.print(message);
        return Date.valueOf(scan.nextLine());
      } catch (IllegalArgumentException e) {
        System.out.println("2019-07-05 형식으로 입력하세요");
      }
    }
  }

  private static int getIntValue(String message) {
    while (true) {
      try {
        System.out.print(message);
        return Integer.parseInt(scan.nextLine());
      } catch (NumberFormatException e) {
        System.out.println("숫자를 입력하세요");
      }
    }
  }

  private static String getStringValue(String message) {
    while (true) {
      System.out.print(message);
      return scan.nextLine();
    }
  }

}
