/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// 애플리케이션 메인클래스
// 애플리케이션을 실행할때 이 클래스를 실행한다.
package com.eomcs.lms;

import java.util.Scanner;
import java.sql.Date;

public class App3 {

  static Scanner scan;

  public static void main(String[] args) {

    scan = new Scanner(System.in);

    int[] no = new int[100];
    String[] contents = new String[100];
    Date[] writeDate = new Date[100];
    int[] viewNum = new int[100];

    int i = 0;
    for (i = 0; i < no.length; i++) {
      no[i] = getIntValue("번호?");
      contents[i] = getStringValue("내용?");
      writeDate[i] = getDateValue("작성일?");
      viewNum[i] = getIntValue("조회수?");

      System.out.println("계속입력하시겠습니까? (y/n)");
      String response = scan.nextLine();

      if (response.equals("n")) {
        break;
      }
    }
    for (int i2 = 0; i2 <= i; i2++) {
      System.out.printf("%s,%s,%s,%s\n", no[i2], contents[i2], writeDate[i2], viewNum[i2]);
    }
  }

  private static int getIntValue(String message) {
    while (true) {
      try {
        System.out.print(message);
        return Integer.parseInt(scan.nextLine());
      } catch (NumberFormatException e) {
        System.out.println("숫자를 입력하세요");
      }
    }
  }

  private static Date getDateValue(String message) {
    while (true) {
      try {
        System.out.print(message);
        return Date.valueOf(scan.nextLine());
      } catch (IllegalArgumentException e) {
        System.out.println("2019-07-05 형식으로 입력하세요");
      }
    }
  }

  private static String getStringValue(String message) {
    while (true) {
      System.out.print(message);
      return scan.nextLine();
    }
  }

}
